language: c
sudo: true
dist: bionic

matrix:
  include:
    - compiler: gcc-8
      env: MAKECMDS="make && make distcheck"
    - compiler: clang
    - compiler: gcc
      env: COVERAGE=t ARGS="--enable-code-coverage" MAKECMDS="make && make check-code-coverage && lcov -l flux*-coverage.info"
    - compiler: clang-6.0
      env: CC=clang-6.0
    - compiler: gcc-8
      env: ARGS="--enable-sanitizers" MAKECMDS="make check"

addons:
  apt:
    packages:
      - gcc-8
      - clang-6.0
      - lcov
      - libjansson-dev

before_install:
  - curl -L -O --insecure https://github.com/jedisct1/libsodium/releases/download/1.0.14/libsodium-1.0.14.tar.gz
  - tar -xf libsodium-1.0.14.tar.gz
  - (cd libsodium-1.0.14 && ./configure --prefix=$HOME/local && make && make install)
  - curl -L -O --insecure https://github.com/dun/munge/releases/download/munge-0.5.13/munge-0.5.13.tar.xz
  - tar -xJf munge-0.5.13.tar.xz
  - (cd munge-0.5.13 && ./configure --prefix=$HOME/local && make && make install)
  - export PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig:$HOME/local/share/pkgconfig
  - PATH=$HOME/local/bin:$HOME/local/sbin:$PATH

script:
  - export FLUX_TESTS_LOGFILE=t
  # Force update to allow version m4 to work
  - ( git fetch --unshallow --tags || true )
  - ./autogen.sh
  - ./configure ${ARGS}
  - eval ${MAKECMDS:-make && make check}

after_success:
  - if test "$COVERAGE" = "t"; then bash <(curl -s https://codecov.io/bash); fi

after_failure:
  - find . -name test-suite.log | xargs -i sh -c 'printf "===XXX {} XXX===";cat {}'
  - find . -name t[0-9]*.output | xargs -i sh -c 'printf "\033[31mFound {}\033[39m\n";cat {}'

before_deploy:
  # Get anchor (formatted properly) and base URI for latest tag in NEWS file
  - export ANCHOR=$(sed -n '/^flux-security version/{s/\.//g; s/\s/-/gp;Q}' NEWS.md)
  - export TAG_URI="https://github.com/${TRAVIS_REPO_SLUG}/blob/${TRAVIS_TAG}"
  - export TARBALL=$(echo flux-security*.tar.gz)
  - ls -l $TARBALL
  - echo "Deploying tag ${TRAVIS_TAG} as $TARBALL"

deploy:
  provider: releases
  skip_cleanup: true
  file: $TARBALL
  prerelease: true
  body: "View [Release Notes](${TAG_URI}/NEWS.md#${ANCHOR}) for flux-security ${TRAVIS_TAG}"
  on:
    # Only deploy from first job in build matrix
    condition: $TRAVIS_JOB_NUMBER = $TRAVIS_BUILD_NUMBER.1
    tags: true
    repo: flux-framework/flux-security
  api_key:
    secure: MRi+vG+IeeqpIow95RIjFTXRsm9dl/9y2C2OODGI5QGa+smZe0w/Tu8AhpcXrrkGSC9n+aQeZXAAQ4Vtik41vAquOCeTyqfXjz1KxuwGQSS5zo5PFwyfJ6YCdYSFoKd7h/Spf0h0ahct5JhTOSJhOIL/h8tD468igMVQrn9BVZ8A1Fq2l+sVHuyjdMQu+cFog8/MfSLC5PyIvm6S86aTN7iWOHl/VWKb3u3XXQoi4/v5IYMGOVNkB46oaZmYEyZ3gol56/3jCzoyduFklz4AZnUhcNTwW5V4923GiQG+Rp6/9b9mdHoip3W3sTfPWyZ6HWMr0TcLzIRVyO5RldLHKLpo/J01LEq3HoZzvU/4pycfaDdtFwsNjtxaDPhdZ69uvFlIgJofPIT740CJQtef00SCRTriGqXueH8nPfFyiywMHaiEzoK5Dx/R5bJMpmCzGEK1gqe6/Dzi5VdqSJ8+D4jITXa+EG2DFb/fKND6gWqCeu4GHk5mi7ayGROC3j1GIoIOCIBDtmUtWBN9159Jh9EnhnT94iV8S8wMH7cYYRJIRNwoe5RqNd9yy/hT0JQtwbdDik2LXLdVnDbchHs3GRP6AQjqiRhx1We2ou+xs6QWDmagoaCDHNclE7JvwXSgLfo5VdQRo6yFmYTnnNvERaBqzTka5Gwbb0O47KpOAfs=
  api-key:
    secure: ZnayFL9PlyWlM+wN1tVTruta64P1ujsQIsteSk08EODIOPIE0LwMg0Dvq905FhMbchq8vYU6KJwTIGWsQ90gwhphKwwMnIH/9o8tq4jEn5R5roFvUlLUNVSl8Q3tibkPdYayOPsV5GRPIpI7tBvbhPbIrET6V67MJplb6rUAcrE/Gcc/QTN9Y1yJxkdiUte/kQN648+9r+Y5JrZ6kpyMx2zK+bSr9K0DVZUnQpy7lakN4mNboWiFdyo2DVPtoQYrkbuXz1nvl0B1fJv0g8vkd4SGK3KSe6b6Wis4BI7yFY3zV3TuVppBdpbARbDp1l4SZwIr3uK36QKdlhaXrIRQsLYOTUF+pCNr1Ox1te0GjbxSypXlr8yxUoQueqOy5lU60Q/Qjz/0KP2VIipV9ZOhaHEGa90nRhYFMLdVLIsCsEQuFpT7KF2T8tNuTOmMC7h69O3DqgfACk5B9sLBszKqPhy1DDjDDo9H1xEnSEg2NVynZiYWP/e1SCmFz3DfDMOyPuEltYG77wVUAl5rTNC9NrIYZmWGCd4mI+fsYqm1LABAcSqEnO0Y67r1rg4VJPf/mMtNnf7OCGN/GlYudyygckv0l4A4ZSiKT1QeJeAQxw99NHULgXIrh8nVnCVE+VeH+uyl7hjaBM2myGpnMb+URAmtubo0YgszXLLElxg2iaM=
