language: c
sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
  packages:

before_install:
  - curl -L -O --insecure https://github.com/jedisct1/libsodium/releases/download/1.0.10/libsodium-1.0.10.tar.gz
  - tar -xf libsodium-1.0.10.tar.gz
  - (cd libsodium-1.0.10 && ./configure --prefix=$HOME/local && make && make install)
  - export PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig:$HOME/local/share/pkgconfig

script:
  - ./autogen.sh
  - ./configure
  - make
  - make check
